<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Respect\\Validation\\' => array($vendorDir . '/respect/validation/library'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'OpMerchantServices\\WooCommercePaymentGateway\\' => array($baseDir . '/src'),
    'OpMerchantServices\\SDK\\' => array($vendorDir . '/op-merchant-services/op-payment-service-php-sdk/src'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
);
